---
common:
  owner: puppetlabs
.gitattributes:
  include:
    '*.rb': 'eol=lf'
    '*.erb': 'eol=lf'
    '*.pp': 'eol=lf'
    '*.sh': 'eol=lf'
    '*.epp': 'eol=lf'
.gitignore:
  required: &ignorepaths
    - '.git/'
    - '.*.sw[op]'
    - '.metadata'
    - '.yardoc'
    - '.yardwarns'
    - '*.iml'
    - '/.bundle/'
    - '/.idea/'
    - '/.vagrant/'
    - '/coverage/'
    - '/bin/'
    - '/doc/'
    - '/Gemfile.local'
    - '/Gemfile.lock'
    - '/junit/'
    - '/log/'
    - '/pkg/'
    - '/spec/fixtures/manifests/'
    - '/spec/fixtures/modules/'
    - '/tmp/'
    - '/vendor/'
    - '/convert_report.txt'
    - '/update_report.txt'
    - '.DS_Store'
    - '.project'
    - '.envrc'
    - '/inventory.yaml'
    - '/spec/fixtures/litmus_inventory.yaml'
.pdkignore:
  required: *ignorepaths
  paths:
    - '/.fixtures.yml'
    - '/Gemfile'
    - '/.gitattributes'
    - '/.gitignore'
    - '/.pdkignore'
    - '/.puppet-lint.rc'
    - '/Rakefile'
    - '/rakelib/'
    - '/.rspec'
    - '/..yml'
    - '/.yardopts'
    - '/spec/'
    - '/.vscode/'
    - '/.sync.yml'
    - '/.devcontainer/'
.yardopts:
  markup: markdown
Rakefile:
  changelog_version_tag_pattern: 'v%s'
  default_disabled_lint_checks:
    - 'relative'
  extras: []
Gemfile:
  required:
    ':development':
      # Json gems should be pinned to their default versions so that users aren't forced to recompile the native extensions.
      # See the following for a version matrix: https://stdgems.org/json/#gem-version
      - gem: json
        version: '= 2.1.0'
        condition: "Gem::Requirement.create(['>= 2.5.0', '< 2.7.0']).satisfied_by?(Gem::Version.new(RUBY_VERSION.dup))"
      - gem: json
        version: '= 2.3.0'
        condition: "Gem::Requirement.create(['>= 2.7.0', '< 3.0.0']).satisfied_by?(Gem::Version.new(RUBY_VERSION.dup))"
      - gem: json
        version: '= 2.5.1'
        condition: "Gem::Requirement.create(['>= 3.0.0', '< 3.0.5']).satisfied_by?(Gem::Version.new(RUBY_VERSION.dup))"
      - gem: json
        version: '= 2.6.1'
        condition: "Gem::Requirement.create(['>= 3.1.0', '< 3.1.3']).satisfied_by?(Gem::Version.new(RUBY_VERSION.dup))"
      - gem: json
        version: '= 2.6.3'
        condition: "Gem::Requirement.create(['>= 3.2.0', '< 4.0.0']).satisfied_by?(Gem::Version.new(RUBY_VERSION.dup))"
      - gem: 'voxpupuli-puppet-lint-plugins'
        version: '~> 5.0'
      - gem: 'facterdb'
        version: '~> 1.18'
      - gem: 'metadata-json-lint'
        version: '~> 3.0'
      - gem: 'puppetlabs_spec_helper'
        version: '~> 6.0'
      - gem: 'rspec-puppet-facts'
        version: '~> 2.0'
      - gem: 'codecov'
        version: '~> 0.2'
      - gem: 'dependency_checker'
        version: '~> 1.0.0'
      - gem: 'parallel_tests'
        version: '= 3.12.1'
      - gem: 'pry'
        version: '~> 0.10'
      - gem: 'simplecov-console'
        version: '~> 0.5'
      - gem: 'puppet-debugger'
        version: '~> 1.0'
      - gem: 'pdk-rubocop'
        version: '= 0.1.0'
      - gem: 'rb-readline'
        version: '= 0.5.5'
        platforms:
          - mswin
          - mingw
          - x64_mingw
    ':system_tests':
      - gem: 'puppet_litmus'
        version: 
        - '~> 1.0'
        platforms: 
          - ruby
          - x64_mingw
      - gem: 'serverspec'
        version: '~> 2.41'
spec/default_facts.yml:
  ipaddress: "172.16.254.254"
  ipaddress6: "FE80:0000:0000:0000:AAAA:AAAA:AAAA"
  is_pe: false
  macaddress: "AA:AA:AA:AA:AA:AA"
spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 0
  mock_with: ":rspec"
  strict_level: ":warning"
  strict_variables: true
.github/workflows/auto_release.yml:
  unmanaged: true
.github/workflows/ci.yml:
  unmanaged: true
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/release.yml:
  unmanaged: true
